"""add drafts

Revision ID: a2b5f90fb0a2
Revises: 9e1172c93959
Create Date: 2026-05-14 22:25:37.058695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b5f90fb0a2'
down_revision: Union[str, None] = '9e1172c93959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_drafts_draft_id'), ['draft_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_case_drafts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_drafts_user_id'))
        batch_op.drop_index(batch_op.f('ix_case_drafts_draft_id'))

    op.drop_table('case_drafts')
    # ### end Alembic commands ###
