from __future__ import annotations

from typing import List, Optional
from datetime import datetime
from pydantic import BaseModel, Field, ConfigDict, field_validator, model_validator
import re
from typing import Optional
from datetime import date
 

CNIC_RE   = re.compile(r'^\d{5}-\d{7}-\d$')
PHONE_RE  = re.compile(r'^(\+92|0)[-\s]?\d{3}[-\s]?\d{7}$')

class CaseHeader(BaseModel):
    """The hero block at the top of the page."""
    model_config = ConfigDict(from_attributes=True)

    id:           str           # external case_id, e.g. "C-2053" auto generated by system
    title:        str
    crime_type:   str
    status:       str
    severity:     str
    investigator: str
    description:  Optional[str] = None

class CaseStats(BaseModel):
    """The 5 dark-blue stat tiles."""
    evidence_collected:  int
    suspects:            int
    investigation_leads: int
    victims:             int
    days_open:           int

class TimelineEventOut(BaseModel):
    """One row in the timeline. Shape mirrors createSystemEvent / createManualEvent
    in caseEventConstants.js — same keys, lowercase, so the existing CaseTimeline
    component renders backend events without changes."""
    model_config = ConfigDict(from_attributes=True, populate_by_name=True)

    id:           str
    caseId:       str           = Field(alias="case_id")
    eventSource:  str           = Field(alias="event_source")    # "system" | "manual"
    eventType:    str           = Field(alias="event_type")
    title:        str
    description:  Optional[str] = None
    officerName:  Optional[str] = Field(default=None, alias="officer_name")
    severity:     str           = "Normal"
    location:     Optional[str] = None
    outcome:      Optional[str] = None
    date:         str           # YYYY-MM-DD
    time:         Optional[str] = None
    createdAt:    Optional[datetime] = Field(default=None, alias="created_at")
    editable:     bool          = True

    # ── NEW: manual-event-only fields (None for system events) ──────────
    attachmentNote:   Optional[str]  = Field(default=None, alias="attachment_note")
    followUpRequired: Optional[bool] = Field(default=False, alias="follow_up_required")
    followUpDate:     Optional[str]  = Field(default=None, alias="follow_up_date")
    # ────────────────────────────────────────────────────────────────────

class CaseDetailResponse(BaseModel):
    header:    CaseHeader
    stats:     CaseStats
    timeline:  List[TimelineEventOut]

class EvidenceInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    evidenceId:    Optional[str] = None
    type:          str                          # EvidenceType.label
    description:   Optional[str] = None
    dateCollected: Optional[str] = None         # YYYY-MM-DD
    collectedBy:   Optional[str] = None
    fileName:      Optional[str] = None
    fileMime:      Optional[str] = None
    photos:         List[str] = []                # list of URLs for image files

class AddEvidenceRequest(BaseModel):
    evidences: List[EvidenceInput]

class VictimInput(BaseModel):
    model_config = ConfigDict(extra="ignore")

    victimId:           Optional[str] = None
    name:               Optional[str] = None
    cnic:               Optional[str] = None
    age:                Optional[int] = None
    gender:             Optional[str] = None
    contact:            Optional[str] = None
    address:            Optional[str] = None
    occupation:         Optional[str] = None
    status:             Optional[str] = None      # VictimStatus.label
    primaryLabel:       Optional[str] = None
    injuryType:         Optional[str] = None
    natureOfInjuries:   Optional[str] = None
    causeOfDeath:       Optional[str] = None
    statement:          Optional[str] = None

class AddVictimRequest(BaseModel):
    victims: List[VictimInput]

class WitnessInput(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    witnessId:           Optional[str]  = None
    name:                Optional[str]  = None
    cnic:                Optional[str]  = None
    age:                 Optional[int]  = None
    gender:              Optional[str]  = None
    contact:             Optional[str]  = None
    address:             Optional[str]  = None
    relationToCase:      Optional[str]  = None
    credibility:         Optional[str]  = None
    description:         Optional[str]  = None
    recorded_by:         Optional[str]  = None        # ← honour caller value
    witnessType:         Optional[str]  = None
    statementDate:       Optional[str]  = None        # YYYY-MM-DD
    anonymous:           Optional[bool] = False
    protection_required: Optional[bool] = Field(default=False, alias="protectionRequired")

    # ── field validators ──────────────────────────────────────────────
    @field_validator("name")
    @classmethod
    def name_not_empty(cls, v):
        if v is not None and v.strip() == "":
            raise ValueError("Name cannot be blank")
        return v

    @field_validator("cnic")
    @classmethod
    def cnic_format(cls, v):
        if v and not CNIC_RE.match(v.strip()):
            raise ValueError("CNIC must be in format 00000-0000000-0")
        return v

    @field_validator("contact")
    @classmethod
    def contact_format(cls, v):
        if v and not PHONE_RE.match(v.strip()):
            raise ValueError("Contact must be a valid Pakistani number, e.g. 0300-1234567")
        return v

    @field_validator("age")
    @classmethod
    def age_min(cls, v):
        if v is not None and v < 7:
            raise ValueError("Witness age must be at least 7 years")
        if v is not None and v > 120:
            raise ValueError("Age must be 120 or less")
        return v

    @field_validator("statementDate")
    @classmethod
    def statement_date_not_future(cls, v):
        if v:
            try:
                d = date.fromisoformat(v)
            except ValueError:
                raise ValueError("statementDate must be YYYY-MM-DD")
            if d > date.today():
                raise ValueError("Statement date cannot be in the future")
        return v

    @model_validator(mode="after")
    def non_anon_requires_name(self):
        if not self.anonymous and not (self.name or "").strip():
            raise ValueError("Name is required for non-anonymous witnesses")
        return self
    
class AddWitnessRequest(BaseModel):
    witnesses: List[WitnessInput]

class AddTimelineResult(BaseModel):
    """Response: every event the request inserted, ready to prepend to
    the frontend's local list. Same shape as AddResult.timeline_events."""
    created_ids:      List[str]   
    timeline_events: List[TimelineEventOut]

class CaseStatusOut(BaseModel):
    id:          int
    code:        str
    label:       str
    is_terminal: bool
    sort_order:  int
    active:      bool

    class Config:
        from_attributes = True


class UpdateCaseStatusRequest(BaseModel):
    status_code: str = Field(..., description="Code of the target status, e.g. 'OPEN'")
    note: Optional[str] = Field(None, max_length=2000)


class UpdateCaseStatusResponse(BaseModel):
    case_id:        str
    old_status:     str
    new_status:     str
    update_note_id: Optional[int]
    updated_at:     datetime